# Generated by Django 4.1 on 2022-08-15 23:44

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the project you want displayed', max_length=20, verbose_name='Title')),
                ('description', models.CharField(help_text='Enter a short description of the project', max_length=30, verbose_name='Description')),
                ('image_url', models.ImageField(default='projects/project_default.jpg', upload_to=projects.models.upload_to, verbose_name='Image')),
                ('project_url', models.URLField(blank=True, help_text='A link to get more info about the project', null=True, verbose_name='Project Link')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
