# Generated by Django 4.1 on 2022-08-12 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_guessed', models.CharField(help_text='The 6th entry or the correct word if user guessed right', max_length=5, verbose_name='Content')),
                ('passed', models.BooleanField(default=False, verbose_name='Passed')),
                ('end', models.DateTimeField(auto_now_add=True, null=True, verbose_name='End')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sittings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['end'],
                'get_latest_by': 'end',
            },
        ),
        migrations.CreateModel(
            name='Wordle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='a description of the wordle', verbose_name='Description')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Ended')], default=0, verbose_name='Status')),
                ('reward', models.PositiveIntegerField(blank=True, help_text='Total reward to be shared among winners', null=True, verbose_name='Reward')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='date created')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date to be published')),
                ('no_of_words', models.PositiveIntegerField(blank=True, help_text='Number of questions to be answered on each attempt.', null=True, verbose_name='Max Questions')),
                ('wordle_id', models.PositiveIntegerField(help_text='Wordle identifier on the blockchain', unique=True, verbose_name='Trivia ID')),
                ('transaction_id', models.CharField(max_length=70, unique=True, verbose_name='Transaction ID')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['pub_date', 'title'],
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Enter the word text that you want displayed', max_length=5, verbose_name='Content')),
                ('found', models.BooleanField(default=False, verbose_name='Found')),
                ('wordle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='words.wordle', verbose_name='Word')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('claimed', models.BooleanField(default=False)),
                ('sitting', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='words.sitting')),
            ],
        ),
        migrations.AddField(
            model_name='sitting',
            name='wordle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sittings', to='words.wordle', verbose_name='Wordle'),
        ),
    ]
