# Generated by Django 4.1 on 2022-08-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_letter_alter_wordle_options_alter_word_wordle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='key',
            field=models.CharField(help_text='Enter the letter that you want displayed', max_length=1, unique=True, verbose_name='Key'),
        ),
    ]
