# Generated by Django 4.1 on 2022-08-15 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_alter_letter_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordle',
            name='no_of_words',
            field=models.PositiveIntegerField(default=1, help_text='Number of words to be attempted for this game.', validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)], verbose_name='Max Words'),
        ),
    ]
