# Generated by Django 4.1 on 2022-08-17 17:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_alter_wordle_no_of_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitting',
            name='wordle',
        ),
        migrations.AddField(
            model_name='sitting',
            name='attempts',
            field=models.PositiveIntegerField(default=1, help_text='Number of words to be attempted for this game.', validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)], verbose_name='Max Words'),
        ),
        migrations.AddField(
            model_name='sitting',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sittings', to='words.word', verbose_name='Word'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wordle',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Ended'), (2, 'Paid')], default=0, verbose_name='Status'),
        ),
    ]
